name: docker-ADO-hosted-undo-pipeline

# This pipeline is for rollbacks. You will have to input a comma-separated list of version scripts
# prior to running it (otherwise it will fail at execution).

trigger: none

pool:
  vmImage: ubuntu-latest
  
parameters:

  - name: cherryPickVersions
    displayName: 'Scripts To Undo: Comma Separated List Of Full Version Numbers'
    default: ''
    type: string

  - name: deploymentStages
    type: object
    default: 

    - stage: 'Test'
      displayName: 'Undo Test'
      variableGroupName: 'test_credentials_variable_group'
    
    - stage: 'Prod'
      displayName: 'Undo Prod'
      variableGroupName: 'prod_credentials_variable_group'

variables:
  FLYWAY_MIGRATIONS_PATH: $(Build.Repository.LocalPath)/migrations
  FLYWAY_CONFIG_FILES: $(Build.Repository.LocalPath)
  FLYWAY: 'docker run --rm -v "$(FLYWAY_MIGRATIONS_PATH)":/flyway/migrations -v "$(FLYWAY_CONFIG_FILES)":/flyway/conf $(FLYWAY_DOCKER_IMAGE) flyway -user="$(userName)" -password="$(password)" -licenseKey=$(FLYWAY_LICENSE_KEY)'
  
  # Contains FLYWAY_LICENSE_KEY, BASELINE_VERSION, FIRST_UNDO_SCRIPT, FLYWAY_DOCKER_IMAGE
  # Make BASELINE_VERSION match the baseline version in your project
  # Make FIRST_UNDO_SCRIPT match the first undo version in your project
  # FLYWAY_DOCKER_IMAGE is currently at: redgate/flyway:9.1.5-azure
  # Look for images at https://hub.docker.com/r/redgate/flyway
  group: flyway_vars
  cherryPickVersions: ${{parameters.cherryPickVersions}}

stages:
  - ${{each stage in parameters.deploymentStages}}:
    
    - stage: ${{stage.stage}} 
      pool: Default
      displayName: ${{stage.displayName}} 
      jobs:
        - job: Undo
          displayName: Undo
          variables:
          - group: ${{stage.variableGroupName}}
          - group: flyway_vars
          steps:
                
            - script: '$(FLYWAY) undo info -url="$(JDBC)" -user="$(userName)" -password="$(password)" -cherryPick="$(cherryPickVersions)" -licenseKey=$(FLYWAY_LICENSE_KEY)'
              failOnStderr: true
              workingDirectory: #Add working directory location if required
              displayName: 'Execute Undo Scripts'