#!/usr/bin/env python3
"""
flyway_parallel_run.py
======================
Single-job alternative to the dynamic child pipeline generated by
generate_pipeline.py.

generate_pipeline.py writes a YAML with one GitLab job per target — GitLab
runners then execute Flyway in parallel across jobs. That works but pays
a runner-startup cost per target (image pull, repo clone, deps install).

For environments with many small target DBs, it's often faster and cheaper
to run flyway against ALL filtered targets from a SINGLE job using a Python
thread pool. This script does exactly that: same registry query + filter
chain as generate_pipeline.py, but instead of emitting YAML it runs

    flyway info -> flyway migrate -> flyway info

against each target concurrently, then prints a per-DB scorecard.

Reuses fetch_targets() + filter_and_build_targets() + REGISTRY config
from generate_pipeline.py so the target set is byte-identical to what
the YAML generator would have produced.

Required environment variables
-------------------------------
REGISTRY_SERVER         SQL Server hostname for the registry database
REGISTRY_USER           Registry login
REGISTRY_PASSWORD       Registry password (mark Protected + Masked in GitLab)
FLYWAY_USER             Login for the target databases
FLYWAY_PASSWORD         Password for the target databases (Protected + Masked)
FLYWAY_EMAIL            Flyway Enterprise license email
FLYWAY_TOKEN            Flyway Enterprise license token

Optional environment variables
-------------------------------
FLYWAY_LOCATIONS        Migration file path (default: filesystem:./migrations)
FILTER_LOCATION         Region to deploy to (default: all)
INCLUDE_REPLICAS        Include replicated DBs (default: false)
MAX_WORKERS             Max parallel Flyway runs (default: 8)
FLYWAY_BASELINE_ON_MIGRATE  default: true
FLYWAY_OUT_OF_ORDER     default: true
FLYWAY_MIXED            default: false

Exits non-zero if any target's Flyway run fails.
"""
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

import pymssql
import generate_pipeline as gp


GREEN = "\033[0;32m"
RED   = "\033[0;31m"
BOLD  = "\033[1m"
RESET = "\033[0m"

MAX_WORKERS = int(os.environ.get("MAX_WORKERS", "8"))

FLYWAY_EMAIL    = os.environ.get("FLYWAY_EMAIL", "")
FLYWAY_TOKEN    = os.environ.get("FLYWAY_TOKEN", "")
FLYWAY_USER     = os.environ.get("FLYWAY_USER", "")
FLYWAY_PASSWORD = os.environ.get("FLYWAY_PASSWORD", "")
FLYWAY_BASELINE = os.environ.get("FLYWAY_BASELINE_ON_MIGRATE", "true")
FLYWAY_OOO      = os.environ.get("FLYWAY_OUT_OF_ORDER", "true")
FLYWAY_MIXED    = os.environ.get("FLYWAY_MIXED", "false")


def run_flyway(target):
    base = [
        "flyway",
        f"-email={FLYWAY_EMAIL}",
        f"-token={FLYWAY_TOKEN}",
        f"-url={target['jdbc_url']}",
        f"-user={FLYWAY_USER}",
        f"-password={FLYWAY_PASSWORD}",
        f"-locations={gp.FLYWAY_LOCATIONS}",
        f"-baselineOnMigrate={FLYWAY_BASELINE}",
        f"-outOfOrder={FLYWAY_OOO}",
        f"-mixed={FLYWAY_MIXED}",
    ]

    def step(cmd):
        return subprocess.run(base + [cmd], capture_output=True, text=True)

    parts = []

    info_pre = step("info")
    parts.append(f"--- flyway info (pre) ---\n{info_pre.stdout}{info_pre.stderr}")
    if info_pre.returncode != 0:
        return _result(target, info_pre.returncode, parts)

    migrate = step("migrate")
    parts.append(f"--- flyway migrate ---\n{migrate.stdout}{migrate.stderr}")
    if migrate.returncode != 0:
        return _result(target, migrate.returncode, parts)

    info_post = step("info")
    parts.append(f"--- flyway info (post) ---\n{info_post.stdout}{info_post.stderr}")
    return _result(target, info_post.returncode, parts)


def _result(target, rc, parts):
    return {
        "name":     target["name"],
        "db":       target["db"],
        "location": target["location"],
        "jdbc_url": target["jdbc_url"],
        "rc":       rc,
        "output":   "\n".join(parts),
    }


def main():
    gp.validate_config()
    for var in ("FLYWAY_USER", "FLYWAY_PASSWORD", "FLYWAY_EMAIL", "FLYWAY_TOKEN"):
        if not os.environ.get(var):
            print(f"ERROR: missing required env var {var}", file=sys.stderr)
            sys.exit(1)

    print(f"{BOLD}{'=' * 60}{RESET}")
    print(f"{BOLD}Flyway Parallel Runner{RESET}")
    print(f"{BOLD}{'=' * 60}{RESET}")
    print(f"Registry: {gp.REGISTRY['server']}:{gp.REGISTRY['port']}/{gp.REGISTRY['database']}")
    print(f"Location: {gp.FILTER_LOCATION}")
    print(f"Workers : {MAX_WORKERS}")
    print()

    try:
        rows = gp.fetch_targets()
    except pymssql.OperationalError as exc:
        print(f"ERROR: cannot connect to registry: {exc}", file=sys.stderr)
        sys.exit(1)
    except pymssql.DatabaseError as exc:
        print(f"ERROR: registry query failed: {exc}", file=sys.stderr)
        sys.exit(1)

    targets = gp.filter_and_build_targets(rows)
    print(f"\nTargets to migrate: {len(targets)}")
    if not targets:
        print("No targets after filtering — nothing to do.")
        return

    results = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        futures = {pool.submit(run_flyway, t): t for t in targets}
        for fut in as_completed(futures):
            results.append(fut.result())

    # Per-DB output (stable order by location, then name)
    results.sort(key=lambda r: (r["location"], r["name"]))
    for r in results:
        color = GREEN if r["rc"] == 0 else RED
        status = "OK" if r["rc"] == 0 else "FAILED"
        print(f"\n{color}{BOLD}[{status}] [{r['location']}] {r['name']} / {r['db']}{RESET}")
        for line in r["output"].splitlines():
            line = line.rstrip()
            if line:
                print(f"  {line}")

    passed = sum(1 for r in results if r["rc"] == 0)
    failed = len(results) - passed
    overall = GREEN if failed == 0 else RED
    print(f"\n{BOLD}{'=' * 60}{RESET}")
    print(f"{BOLD}Results: {overall}{passed}/{len(results)} succeeded, {failed}/{len(results)} failed{RESET}")
    print(f"{BOLD}{'=' * 60}{RESET}")

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
