image: openjdk:11

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - echo 'Building and testing...'
          # Put your build and test scripts here
          
    - step:
        name: Migrate database with Flyway
        image: boxfuse/flyway
        script:
          - echo 'Migrating database...'
          - flyway -url=$DATABASE_URL -user=$DATABASE_USER -password=$DATABASE_PASSWORD migrate
        services:
          - database

definitions:
  services:
    database:
      image: postgres
      environment:
        POSTGRES_DB: 'your_database'
        POSTGRES_USER: $DATABASE_USER
        POSTGRES_PASSWORD: $DATABASE_PASSWORD
