INSERT INTO Animal (type, classification)
VALUES ('Snake', 'Reptile'),
       ('Lion', 'Mammal'),
       ('Whale', 'Mammal'),
       ('Shark', 'Fish'),
       ('Eagle', 'Bird'),
       ('Crocodile', 'Reptile'),
       ('Dolphin', 'Mammal'),
       ('Penguin', 'Bird'),
       ('Ostrich', 'Bird'),
       ('Lizard', 'Reptile'),
       ('Turtle', 'Reptile'),
       ('Frog', 'Amphibian'),
       ('Salamander', 'Amphibian'),
       ('Toad', 'Amphibian'),
       ('Tortoise', 'Reptile'),
       ('Alligator', 'Reptile'),
       ('Chameleon', 'Reptile'),
       ('Iguana', 'Reptile'),
       ('Gecko', 'Reptile'),
       ('Komodo Dragon', 'Reptile'),
       ('Anaconda', 'Reptile'),
       ('Python', 'Reptile'),
       ('Boa Constrictor', 'Reptile'),
       ('Cobra', 'Reptile'),
       ('Rattlesnake', 'Reptile'),
       ('Viper', 'Reptile'),
       ('Mamba', 'Reptile'),
       ('Coral Snake', 'Reptile'),
       ('Garter Snake', 'Reptile'),
       ('Rat Snake', 'Reptile'),
       ('Milk Snake', 'Reptile'),
       ('King Snake', 'Reptile'),
       ('Gila Monster', 'Reptile'),
       ('Bearded Dragon', 'Reptile'),
       ('Tegu', 'Reptile'),
       ('Monitor Lizard', 'Reptile'),
       ('Chinchilla', 'Mammal'),
       ('Hamster', 'Mammal'),
       ('Guinea Pig', 'Mammal'),
       ('Rabbit', 'Mammal'),
       ('Mouse', 'Mammal'),
       ('Rat', 'Mammal'),
       ('Hedgehog', 'Mammal'),
       ('Ferret', 'Mammal'),
       ('Gerbil', 'Mammal'),
       ('Sugar Glider', 'Mammal'),
       ('Squirrel', 'Mammal'),
       ('Chimpanzee', 'Mammal'),
       ('Gorilla', 'Mammal'),
       ('Orangutan', 'Mammal'),
       ('Baboon', 'Mammal'),
       ('Mandrill', 'Mammal'),
       ('Lemur', 'Mammal'),
       ('Tamarin', 'Mammal');