name: Flyway GitHub Actions QA Workflow
on:
  push:
    branches:
      - QA
    paths:
      - "migrations/**"

env:
  # Variables - Create these in Project Settings > Variables > Actions
  EMAIL: ${{ vars.USER_EMAIL }}
  JDBC_QA: ${{ vars.JDBC_QA }}
  # Secrets - Create these in Project Settings > Secrets > Actions
  TOKEN: ${{ secrets.FLYWAY_TOKEN }}
  DB_USER_QA: ${{ secrets.DB_USER_NAME_QA }}
  DB_USER_PW_QA: ${{ secrets.DB_USER_PW_QA }}

jobs:
  flyway-deploy-qa:
    runs-on: self-hosted # Runner to execute the job
    # runs-on: ubuntu-latest
    defaults:
      run:
        shell: cmd # Default shell. Use Windows Command Prompt

    steps: # Steps are the individual tasks that are executed in the job
      - uses: actions/checkout@v4 # Check out the repository
        with: # Additional options for the action
          ref: "QA" # Branch to check out

      - name: Deploy to QA # Step to run Flyway migrations
        # To use username and password instead of windows integrated security Ensure that SQL Server is configured to allow SQL Server authentication. You can check this in SQL Server Management Studio (SSMS) under the server properties -> Security -> Server authentication. Ensure "SQL Server and Windows Authentication mode" is selected.
        run: flyway -email=${{ env.EMAIL }} -token=${{ env.TOKEN }} info migrate info -user=${{ env.DB_USER_QA }} -password=${{ env.DB_USER_PW_QA }} -url=${{ env.JDBC_QA }} -IAgreeToTheEula -locations="filesystem:${{ github.workspace }}/migrations" -configFiles="${{ github.workspace }}/flyway.toml" -baselineOnMigrate=true -errorOverrides=S0001:0:I-
        working-directory: ./migrations
