parameters:
- name: stage
  default: Build
- name: displayName
  default: Deploy Build
- name: cleanBuildDB
  default: false
- name: targetCredentials
  default: ''
- name: pipelineParameters
  default: ''
- name: executeStaticCodeAnalysis
  default: false
- name: installFlyway
  default: 'true'
  
stages:
  - stage: Build
    pool: $(AGENT_POOL)
    displayName: ${{parameters.displayName}} 
    jobs:
    - job: Build
      variables:
      - group: ${{parameters.targetCredentials}}
      - group: ${{parameters.pipelineParameters}}
      - group: redgate_global_vars
      steps:
        # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/checkout-path.md#control-the-checkout-location-of-code
        - checkout: templates
        - checkout: self
          name: source

        - ${{if eq( parameters.installFlyway, true)}}:
          - job: InstallFlyway
            displayName: Install Flyway
            variables:
            - group: ${{parameters.targetCredentials}}
            - group: ${{parameters.pipelineParameters}}
            - group: redgate_global_vars
            steps:

              # Linux
              - script: |     
                echo "Downloading and unzipping Flyway ${FLYWAY_VERSION}..."
                curl -sS https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}-linux-x64.tar.gz | tar xz >/dev/null    
                export PATH="$(System.DefaultWorkingDirectory)/flyway-${FLYWAY_VERSION}:$PATH"  
                flyway --version
              displayName: 'Flyway Install'
              continueOnError: false
              env:
                FLYWAY_VERSION: "10.17.1"
              
              # Windows
              - task: PowerShell@2
                condition: eq( variables['Agent.OS'], 'Windows_NT' )
                displayName: Install Flyway On Windows
                inputs:
                  targetType: 'filePath'
                  filePath: 'InstallFlywayWindows.ps1'
        
        - script: '$(FLYWAY) clean info -url="$(target_database_JDBC)"'
          continueOnError: false
          displayName: 'Clean Build DB'
          condition: and(succeeded(), eq('${{ parameters.cleanBuildDB }}', true))
          env:
            FLYWAY_CLEAN_DISABLED: false

        - script: '$(FLYWAY) info check -environment="target" -environments.target.url="$(target_database_JDBC)" -environments.check.url="$(check_JDBC)" -check.buildEnvironment="check" -check.rulesLocation="$(Build.SourcesDirectory)\templates\rules" -code -reportFilename="$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-Code-Analysis.html"'
          continueOnError: false
          workingDirectory: '$(WORKING_DIRECTORY)\$(Build.Repository.Name)'
          displayName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
          condition: and(succeeded(), eq('${{ parameters.executeStaticCodeAnalysis }}', true))
          env:
            FLYWAY_CLEAN_DISABLED: false
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish $(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
          condition: and(succeeded(), eq('${{ parameters.executeStaticCodeAnalysis }}', true))
          inputs:
            ArtifactName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            PathtoPublish: '$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-Code-Analysis.html'
        
        - script: '$(FLYWAY) migrate info -url="$(target_database_JDBC)"'
          continueOnError: false
          displayName: 'Validate Migrate Scripts'

        - script: '$(FLYWAY) undo info -url="$(target_database_JDBC)" -target="$(FIRST_UNDO_SCRIPT)"?'
          continueOnError: true
          displayName: 'Validate Undo Scripts'