parameters:
- name: stage
  default: Build
- name: displayName
  default: Deploy Build
- name: cleanBuildDB
  default: false
- name: targetCredentials
  default: ''
- name: pipelineParameters
  default: ''
- name: executeStaticCodeAnalysis
  default: false
  
stages:
  - stage: Build
    pool: $(AGENT_POOL)
    displayName: ${{parameters.displayName}} 
    jobs:
    - job: Build
      variables:
      - group: ${{parameters.targetCredentials}}
      - group: ${{parameters.pipelineParameters}}
      - group: redgate_global_vars
      steps:
        # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/checkout-path.md#control-the-checkout-location-of-code
        - checkout: templates
        - checkout: self
          name: source
        
        - script: '$(FLYWAY) clean info -url="$(target_database_JDBC)"'
          continueOnError: false
          displayName: 'Clean Build DB'
          condition: and(succeeded(), eq('${{ parameters.cleanBuildDB }}', true))
          env:
            FLYWAY_CLEAN_DISABLED: false

        - script: '$(FLYWAY) migrate info -url="$(target_database_JDBC)"'
          continueOnError: false
          displayName: 'Validate Migrate Scripts'

        - script: '$(FLYWAY) info check -check.rulesLocation="$(Build.SourcesDirectory)\templates\rules" -code -url="$(target_database_JDBC)" -reportFilename="$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-Code-Analysis.html"  -locations="filesystem:$(WORKING_DIRECTORY)\$(Build.Repository.Name)\migrations"'
          continueOnError: false
          workingDirectory: '$(WORKING_DIRECTORY)\$(Build.Repository.Name)'
          displayName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
          condition: and(succeeded(), eq('${{ parameters.executeStaticCodeAnalysis }}', true))
          env:
            FLYWAY_CLEAN_DISABLED: false
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish $(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
          condition: and(succeeded(), eq('${{ parameters.executeStaticCodeAnalysis }}', true))
          inputs:
            ArtifactName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            PathtoPublish: '$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-Code-Analysis.html'

        - script: '$(FLYWAY) undo info -url="$(target_database_JDBC)" -target="$(FIRST_UNDO_SCRIPT)"?'
          continueOnError: true
          displayName: 'Validate Undo Scripts'
