parameters:
- name: stage
  default: stage
- name: displayName
  default: Deploy
- name: dependsOn
  default: ''
- name: pauseForCodeReview
  default: false
- name: failReleaseIfDriftDetected
  default: false
- name: staticCodeAnalysis
  default: false
- name: staticCodeAnalysisOnly
  default: false
- name: generateReport                              #This is the primary flag to turn off reports. TODO: Sanitize number of variables used here.
  default: true
- name: targetCredentials
  default: ''
- name: pipelineParameters
  default: ''
- name: agentPool
  default: 'default'
- name: installFlyway
  default: false
- name: notificationsGroup
  default: ''                                       #[Microsoft]\Pipeline Developers 
                                                    #syntax discussions here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/13320, https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/manual-validation-v0?view=azure-pipelines

stages:
  - stage: ${{parameters.stage}} 
    pool: $(AGENT_POOL)                             # ${{parameters.agentPool}} if wish to parameterize and pass in
    displayName: ${{parameters.displayName}} 
    dependsOn: ${{parameters.dependsOn}} 
    jobs:

    - ${{if eq( parameters.installFlyway, true)}}:
      - job: InstallFlyway
        displayName: Install Flyway
        variables:
        - group: ${{parameters.targetCredentials}}
        - group: ${{parameters.pipelineParameters}}
        - group: redgate_global_vars
        steps:

          - checkout: templates
          - checkout: self
            name: source

          # Linux
          - task: Bash@3  
            condition: eq( variables['Agent.OS'], 'Linux' )
            displayName: Install Flyway On Unix
            inputs:
              targetType: 'filePath'
              filePath: '$(Build.SourcesDirectory)\templates\InstallFlywayUnix.sh'
          
          # Windows
          - task: PowerShell@2
            condition: eq( variables['Agent.OS'], 'Windows_NT' )
            displayName: Install Flyway On Windows
            inputs:
              targetType: 'filePath'
              filePath: '$(Build.SourcesDirectory)\templates\InstallFlywayWindows.ps1'
    
    - ${{if eq( parameters.installFlyway, false)}}:
      - job: InstallFlyway
        displayName: Install Flyway - Disabled
        pool: server

    - ${{if and(eq( parameters.generateReport, true), eq(parameters.staticCodeAnalysisOnly, true))}}:
      - job: ChangeReport
        displayName: Change Report With Code Analysis
        dependsOn: 'InstallFlyway'
        variables:
        - group: ${{parameters.targetCredentials}}
        - group: ${{parameters.pipelineParameters}}
        - group: redgate_global_vars
        steps:
          # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/checkout-path.md#control-the-checkout-location-of-code
          - checkout: templates
          - checkout: self
            name: source
          
          - script: '$(FLYWAY) info check -code -environments.target.url="$(target_database_JDBC)" -check.rulesLocation="$(Build.SourcesDirectory)\templates\rules" -reportFilename="$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-$(DRIFT_AND_CHANGE_REPORT)"'
            continueOnError: false
            workingDirectory: '$(WORKING_DIRECTORY)\$(Build.Repository.Name)'
            displayName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            env:
              FLYWAY_CLEAN_DISABLED: false
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish $(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            condition: always()
            inputs:
              ArtifactName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
              PathtoPublish: '$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-$(DRIFT_AND_CHANGE_REPORT)'

    - ${{if and(eq(parameters.staticCodeAnalysis, true), eq( parameters.generateReport, true), eq(parameters.staticCodeAnalysisOnly, false))}}:
      - job: ChangeReport
        displayName: Change Report With Code Analysis
        dependsOn: 'InstallFlyway'
        variables:
        - group: ${{parameters.targetCredentials}}
        - group: ${{parameters.pipelineParameters}}
        - group: redgate_global_vars
        steps:
          # https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/checkout-path.md#control-the-checkout-location-of-code
          - checkout: templates
          - checkout: self
            name: source
          
          - script: '$(FLYWAY) info check -dryrun -drift -changes -code -environments.target.url="$(target_database_JDBC)" -environments.check.url="$(check_JDBC)" -check.buildEnvironment="check" -check.rulesLocation="$(Build.SourcesDirectory)\templates\rules" -check.failOnDrift="${{parameters.failReleaseIfDriftDetected}}" -reportFilename="$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-$(DRIFT_AND_CHANGE_REPORT)"'
            continueOnError: false
            workingDirectory: '$(WORKING_DIRECTORY)\$(Build.Repository.Name)'
            displayName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            env:
              FLYWAY_CLEAN_DISABLED: false
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish $(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            condition: always()
            inputs:
              ArtifactName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
              PathtoPublish: '$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-$(DRIFT_AND_CHANGE_REPORT)'

    - ${{if and(eq( parameters.staticCodeAnalysis, false), eq( parameters.generateReport, true), eq(parameters.staticCodeAnalysisOnly, false))}}:
      - job: ChangeReport
        displayName: Change Report
        dependsOn: 'InstallFlyway'
        variables:
        - group: ${{parameters.targetCredentials}}
        - group: ${{parameters.pipelineParameters}}
        - group: redgate_global_vars
        steps:

          - checkout: templates
          - checkout: self
            name: source

          - script: '$(FLYWAY) info check -dryrun -drift -changes -environments.target.url="$(target_database_JDBC)" -environments.check.url="$(check_JDBC)" -check.buildEnvironment="check" -check.rulesLocation="$(Build.SourcesDirectory)\templates\rules" -check.failOnDrift="${{parameters.failReleaseIfDriftDetected}}" -reportFilename="$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-$(DRIFT_AND_CHANGE_REPORT)"'
            workingDirectory: '$(WORKING_DIRECTORY)'
            continueOnError: false
            displayName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            env:
              FLYWAY_CLEAN_DISABLED: false
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish $(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
            condition: always()
            inputs:
              ArtifactName: '$(DRIFT_AND_CHANGE_REPORT_DISPLAY_NAME)'
              PathtoPublish: '$(System.ArtifactsDirectory)\$(databaseName)-$(Build.BuildId)-$(DRIFT_AND_CHANGE_REPORT)'
    
    - ${{if eq(parameters.generateReport, false)}}:
      - job: ChangeReport
        displayName: Change Report
        dependsOn: 'InstallFlyway'
        variables:
        - group: ${{parameters.targetCredentials}}
        - group: ${{parameters.pipelineParameters}}
        - group: redgate_global_vars
        steps:
          - powershell: |
              Write-Host "##[warning]For reporting documentation see here: https://documentation.red-gate.com/fd/check-224919699.html"
            workingDirectory: '$(WORKING_DIRECTORY)'
            continueOnError: true
            displayName: 'No Reports Generated'

          # - bash: |
          #     echo "##[warning]For reporting documentation see here: https://documentation.red-gate.com/fd/check-224919699.html"
          #   workingDirectory: '$(WORKING_DIRECTORY)'
          #   continueOnError: true
          #   displayName: 'No Reports Generated'

    - ${{if eq(parameters.pauseForCodeReview, true)}}:
      - job: CodeReview
        displayName: Code Review
        dependsOn: 'ChangeReport'
        pool: server
        steps:
          - task: ManualValidation@0
            displayName: 'Review Change Report Prior To Release'
            timeoutInMinutes: 4320 # job times out in 1 hour
            inputs:
              notifyUsers: ${{parameters.notificationsGroup}}
              instructions: 'Review changes'
    
    - ${{if eq(parameters.pauseForCodeReview, false)}}:
      - job: CodeReview
        pool: server
        displayName: Skipping Code Review
        dependsOn: 'ChangeReport'
    
    - job: Deploy
      displayName: Deployment
      dependsOn: 'CodeReview'
      variables:
      - group: ${{parameters.targetCredentials}}
      - group: ${{parameters.pipelineParameters}}
      - group: redgate_global_vars
      steps:

        - checkout: templates
        - checkout: self
          name: source

        - script: '$(FLYWAY) info repair migrate -outOfOrder=true info -environments.target.url="$(target_database_JDBC)"'
          workingDirectory: $(WORKING_DIRECTORY)
          displayName: ${{parameters.displayName}}
          continueOnError: false
          env:
            FLYWAY_CLEAN_DISABLED: true # clean drops a target DB schema, keep disabled except for build step