parameters:
- name: stage
  default: stage
- name: displayName
  default: Deploy
- name: dependsOn
  default: ''
- name: pauseForCodeReview
  default: false
- name: failReleaseIfDriftDetected
  default: false
- name: generateDriftAndChangeReport
  default: false
- name: staticCodeAnalysis
  default: false
- name: targetCredentialsVariableGroup
  default: ''
- name: pipelineParamsVariableGroup
  default: ''

stages:
  - stage: ${{parameters.stage}} 
    pool: $(AGENT_POOL)
    displayName: ${{parameters.displayName}} 
    jobs:
    - job: Deploy
      displayName: Deployment
      variables:
      - group: ${{parameters.targetCredentialsVariableGroup}}
      - group: rg_flyway_vars
      - group: ${{parameters.pipelineParamsVariableGroup}}
      steps:

        - script: '$(FLYWAY) info migrate -outOfOrder=true info -url="$(target_database_JDBC)"'
          workingDirectory: $(WORKING_DIRECTORY)
          displayName: ${{parameters.displayName}}
          failOnStderr: true
          env:
            FLYWAY_CLEAN_DISABLED: true # clean drops a target DB schema, keep disabled except for build step