name: Build Gradle project

on:
  push:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run RGClone with Flyway in Spring Boot
      run: |
        CONTAINERNAME="test_${{ github.run_id }}_${{ github.run_attempt }}"
        chmod +x ./gradle/gradlew
        cd ./gradle
        ./gradlew startCloneAndFlywayMigrate -PrgCloneEndpoint="${{ secrets.RGCLONE_ENDPOINT }}" -PrgCloneToken="${{ secrets.RGCLONE_TOKEN }}" -PcontainerName="${CONTAINERNAME}" -PflywayLicenseKey=${{ secrets.FLYWAY_LICENCE}} -PrgCloneDbPassword=${{ secrets.RGCLONE_DB_PASSWORD}}
